### PR TITLE
Add dynamic sponsor generation

### LINKED ISSUE #25: Move sponsors to front matter

### PR DESCRIPTION
**Pull request by matthewghuang**
This is my first time  using Hugo's templating features, let me know if I'm doing anything wrong.

Fixes #25

### CODE REVIEW

**Review by kx-chen — COMMENTED** [review]
Looks good at a glance! :) 

Any thoughts about putting the data into Hugo's `data` directory instead of the front matter? Not too sure about Hugo's features as well lol

**Comment by matthewghuang** [comment]
I should really look into Hugo's directory structure, the `data` directory is pretty rad 😎.

**Comment by kx-chen** [comment]
Opened #27 since I forgot to commit the "data" directory last time.

**Review by kx-chen — DISMISSED** [review]
Tested it locally, works on my machine. Feel free to merge as is, or add in the `data` directory to this PR too. Up to you I guess

**Pull request merged**
